from typing import Any, Optional
from pydantic import BaseModel, ConfigDict, Field
from app.core.config import settings


class ChatRequest(BaseModel):
    """Incoming analytics chat request."""

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "prompt": "What are the top 10 customers by revenue last month?",
                "session_id": "abc-123",
                "table_pattern": "%",
            }
        }
    )

    prompt: str = Field(
        ...,
        min_length=1,
        max_length=8192,
        description="Natural-language analytics question to answer with SQL.",
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Client-supplied identifier used to correlate multi-turn conversations.",
    )
    model: Optional[str] = Field(
        default=settings.GROQ_DEFAULT_MODEL,
        description="Groq model identifier to use for SQL generation and explanation.",
    )
    table_pattern: str = Field(
        default="%",
        description="SQL LIKE pattern applied to TABLE_NAME when fetching schema metadata (e.g. 'SALES%').",
    )
    database: Optional[str] = Field(
        default=None,
        description="Snowflake database to query. Defaults to the value in settings.",
    )
    schema_name: Optional[str] = Field(
        default=None,
        description="Snowflake schema to query. Defaults to the value in settings.",
    )


class ChatResponse(BaseModel):
    """Structured response returned by the /chat endpoint."""

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "session_id": "abc-123",
                "model": "llama-3.3-70b-versatile",
                "question": "What are the top 10 customers by revenue last month?",
                "generated_sql": "SELECT customer_id, SUM(amount) AS revenue FROM orders ...",
                "snowflake_data": [{"customer_id": 1, "revenue": 98000.0}],
                "row_count": 10,
                "ai_response": "The top customer generated $98,000 in revenue last month...",
                "dialect": "Snowflake SQL",
                "timestamp": "2026-05-25T10:00:00+00:00",
                "success": True,
                "error": None,
            }
        }
    )

    session_id: Optional[str] = Field(
        default=None,
        description="Echoed session ID from the request.",
    )
    model: Optional[str] = Field(
        default=None,
        description="Groq model that produced the SQL and explanation.",
    )
    question: str = Field(
        description="Original natural-language question from the request.",
    )
    generated_sql: str = Field(
        description="SQL query generated by the LLM and executed against Snowflake.",
    )
    snowflake_data: list[dict[str, Any]] = Field(
        description="Raw query results returned from Snowflake as JSON-serialisable records.",
    )
    row_count: int = Field(
        description="Total number of rows returned by the query.",
    )
    ai_response: str = Field(
        description="Plain-English business explanation of the query results, generated by the LLM.",
    )
    dialect: str = Field(
        default="Snowflake SQL",
        description="SQL dialect used for query generation.",
    )
    timestamp: str = Field(
        description="UTC ISO-8601 timestamp of when the response was produced.",
    )
    success: bool = Field(
        description="True when the full pipeline completed without errors.",
    )
    error: Optional[str] = Field(
        default=None,
        description="Human-readable error message when success is False, null otherwise.",
    )
