name: Debug Workflow

on:
  push:
    branches:
      - test

  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Debug
        run: echo "GitHub Actions is working"